### ISSUE TITLE
Error with pydot in generate-graph.py

### ISSUE THREAD

**Issue by clemisch** [MegaManSec/SSH-Snake#5]
```
$ python3 generate-graph.py --file ~/snake.log --with-users --format dot
Traceback (most recent call last):
  File "/home/clem/git/SSH-Snake/tools/generate-graph.py", line 110, in <module>
    nx.drawing.nx_pydot.write_dot(graph, output_dot_file_path)
  File "/home/clem/git/SSH-Snake/tools/venv/lib64/python3.12/site-packages/networkx/utils/decorators.py", line 770, in func
    return argmap._lazy_compile(__wrapper)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<class 'networkx.utils.decorators.argmap'> compilation 5", line 5, in argmap_write_dot_1
  File "/home/clem/git/SSH-Snake/tools/venv/lib64/python3.12/site-packages/networkx/drawing/nx_pydot.py", line 51, in write_dot
    P = to_pydot(G)
        ^^^^^^^^^^^
  File "/home/clem/git/SSH-Snake/tools/venv/lib64/python3.12/site-packages/networkx/drawing/nx_pydot.py", line 265, in to_pydot
    raise ValueError(
ValueError: Node names and attributes should not contain ":" unless they are quoted with "".                For example the string 'attribute:data1' should be written as '"attribute:data1"'.                Please refer https://github.com/pydot/pydot/issues/258
```

**Comment by MegaManSec** [comment]
Thanks for the report! Fixing..
